# Generated by Django 3.1 on 2020-08-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
